package com.qlda.workflowservice.exception;

public enum ErrorCode {
    WORKFLOW_NOT_FOUND,
    WORKFLOW_STEP_NOT_FOUND,
    PROCESSING_NOT_FOUND,
    DOCUMENT_NOT_FOUND,
    USER_NOT_FOUND,
    INVALID_WORKFLOW_STATUS,
    APPROVAL_FAILED,
    TRANSFER_FAILED,
    SLA_NOT_FOUND,
    FORBIDDEN,
    INTERNAL_SERVER_ERROR,
    INVALID_REQUEST
}
