package com.qlda.aiservice.exception;

public enum ErrorCode {
    AI_PROCESSING_FAILED,
    DOCUMENT_NOT_FOUND,
    AI_RESULT_NOT_FOUND,
    OCR_FAILED,
    SUMMARY_FAILED,
    CLASSIFICATION_FAILED,
    METADATA_EXTRACTION_FAILED,
    SEMANTIC_SEARCH_FAILED,
    CHATBOT_FAILED,
    ACCESS_DENIED,
    INVALID_FILE_FORMAT,
    INTERNAL_SERVER_ERROR
}
